language: node_js
node_js:
  - "14.16.0"
sudo: false
 
branches:
  only:
  - master
 
cache:
  directories:
    - node_modules
 
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: courier-app
