language: node_js
node_js:
  - 14
sudo: false
 
branches:
  only:
  - master
 
cache:
  directories:
    - node_modules
 
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: courier-app
